project_name/apps/about/urls.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="about/about.html"), name="about"),
    url(r"^terms/$", TemplateView.as_view(template_name="about/terms.html"), name="terms"),
    url(r"^privacy/$", TemplateView.as_view(template_name="about/privacy.html"), name="privacy"),
)

project_name/apps/api/urls.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns("",
    url(r"^$", views.ApiRoot.as_view(), name="api_root"),
)

project_name/apps/home/urls.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns("",
    url(r"^$", views.select_view, name="home"),
)

project_name/urls.py
#-*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from sitemaps import sitemaps

#handler500 = "util.views.server_error"

admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$",          include("home.urls")),
    url(r"^about/",     include("about.urls", namespace="about")),
    url(r"^account/", include("account.urls")),
    url(r"^api/", include("api.urls")),
    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    url(r"^sitemap\.xml$", "django.contrib.sitemaps.views.sitemap", kwargs={"sitemaps": sitemaps}),
    url(r"^admin/", include(admin.site.urls)),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_name/apps/about/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

project_name/apps/api/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

project_name/apps/core/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

project_name/apps/home/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

project_name/apps/util/models.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

project_name/apps/api/views.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView


class ApiRoot(APIView):
    """
    The root view for the rest api.
    """

    permissions = (IsAuthenticated, )

    def build_url(self, request, urlname):
        if isinstance(urlname, dict):
            return reverse(request=request, **urlname)
        return reverse(urlname, request=request)

    def get(self, request):
        data = [{
            "name": name,
            "url": self.build_url(request, urlname)
        } for name, urlname in [
            # ("Object list", "api_object_list"),
        ]]
        return Response(data)

project_name/apps/home/views.py
#-*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.views.generic import TemplateView, DetailView


class IndexView(TemplateView):
    template_name = "home/index.html"


class HomepageView(DetailView):
    template_name = "home/homepage.html"
    context_object_name = "profile"

    def get_object(self, queryset=None):
        return self.request.user

index = IndexView.as_view()
homepage = HomepageView.as_view()


def select_view(request, *args, **kwargs):
    if request.user.is_authenticated():
        return homepage(request, *args, **kwargs)
    return index(request, *args, **kwargs)

project_name/templates/_account_bar.html
{% load i18n %}
{% load url from future %}
<ul class="nav pull-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			    {{ user.get_full_name|default:user.email }}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url "account_settings" %}"><i class="icon-cog"></i> {% trans "Settings" %}</a></li>
                {% if request.user.is_staff %}
                    <li><a href="{% url "admin:index" %}"><i class="icon-cog"></i> {% trans "Admin" %}</a></li>
                {% endif %}
                <li class="divider"></li>
                <li><a href="{% url "account_logout" %}"><i class="icon-off"></i> {% trans "Log out" %}</a></li>
            </ul>
        </li>
    {% else %}
        <li><a class="account-login" href="{% url "account_login" %}"><span class="label label-info">{% trans "Log in" %}</span></a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li class="navbar-text">{% trans "or" %}</li>
            <li><a class="account-signup" href="{% url "account_signup" %}"><span class="label label-success">{% trans "Sign up" %}</span></a></li>
        {% endif %}
    {% endif %}
</ul>

project_name/templates/_footer.html
{% load i18n %}
{% load url from future %}
<div class="container">
    <div class="row">
        <div class="span12">
            <p class="muted credit">
                Copyright &copy; <a href="/">{% trans "Project Name" %}</a> |
                <a href="{% url "about:about" %}">{% trans "About" %}</a> |
                <a href="{% url "about:terms" %}">{% trans "Terms of Use" %}</a> |
                <a href="{% url "about:privacy" %}">{% trans "Privacy Policy" %}</a> |
                <a href="{% url "account_signup" %}">{% trans "Sign Up" %}</a>
            </p>
        </div>
    </div>
</div>

project_name/templates/_messages.html
{% for message in messages %}
    <div class="alert fade in {% if message.tags %} alert-{{ message.tags }}{% endif %}">
        <a class="close" href="#" data-dismiss="alert">&times;</a>
        {{ message }}
    </div>
{% endfor %}

project_name/templates/about/about.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "About" %}{% endblock %}

{% block body %}
    <h1>{% trans "About" %}</h1>
{% endblock %}

project_name/templates/about/privacy.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Privacy Policy" %}{% endblock %}

{% block body %}
    <h1>{% trans "Privacy Policy" %}</h1>
{% endblock %}

project_name/templates/about/terms.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Terms of Service" %}{% endblock %}

{% block body %}
    <h1>{% trans "Terms of Service" %}</h1>
{% endblock %}

project_name/templates/assets/scripts.html
{% load static compress %}
{% compress js %}
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-transition.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-alert.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-button.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-carousel.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-collapse.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-dropdown.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-modal.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-tooltip.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-popover.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-scrollspy.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-tab.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-typeahead.js" %}"></script>
<script type="text/javascript" src="{% static "components/bootstrap/js/bootstrap-affix.js" %}"></script>
{#<script type="text/javascript" src="{% static "components/jquery-pjax/jquery.pjax.js" %}"></script>#}
<script type="text/javascript" src="{% static "components/underscore/underscore.js" %}"></script>
<script type="text/javascript" src="{% static "components/backbone/backbone.js" %}"></script>
<script type="text/javascript" src="{% static "components/json2/json2.js" %}"></script>
<script type="text/javascript" src="{% static "js/lib/ajax.js" %}"></script>
<script type="text/javascript" src="{% static "js/lib/forms.js" %}"></script>
<script type="text/javascript" src="{% static "js/modules/app.js" %}"></script>
<script type="text/javascript" src="{% static "js/script.js" %}"></script>
{% endcompress %}

project_name/templates/assets/styles.html
{% load static compress %}
{% compress css %}
<link rel="stylesheet" type="text/less" href="{% static "less/style.less" %}" />
{% endcompress %}

project_name/templates/home/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Home" %}{% endblock %}

{% block content %}
    <h1>{% trans "Welcome" %} {{ profile.get_full_name }}</h1>
{% endblock %}

project_name/templates/home/index.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Hello" %}{% endblock %}
{% block body_id %}front-page{% endblock %}

{% block content %}
    <header class="bannerhead">
        <div class="well banner"><h1>{% trans "Hello" %}</h1></div>
    </header>
{% endblock %}

project_name/templates/sidebar_base.html
{% extends "site_base.html" %}

{% block content_base %}
    <div class="span8">
        {% block body %}
            {% block content %}{% endblock %}
        {% endblock %}
    </div>
    <div class="span4">
        {% block sidebar %}{% endblock %}
    </div>
{% endblock %}

project_name/templates/site_base.html
{% extends "theme_base.html" %}

{% block content_base %}
    <div class="span12">
        {% block body %}
            {% block content %}{% endblock %}
        {% endblock %}
    </div>
{% endblock %}

project_name/templates/subnav_base.html
{% extends "site_base.html" %}

{% block content_base %}
    <div class="span2">
        {% block subnav_base %}
            {% block subnav %}{% endblock %}
        {% endblock %}
    </div>
    <div class="span10">
        {% block body %}
            {% block content %}{% endblock %}
        {% endblock %}
    </div>
{% endblock %}

project_name/templates/theme_base.html
{% load static i18n compress %}{% load url from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# profile: http://ogp.me/ns/profile#">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="imagetoolbar" content="false" />
    <title>{% block head_title_base %}{% block head_title %}{% endblock %} | {% trans "Project Name" %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "favicon.ico" %}" />
    <meta name="description" content="{% block meta_description %}{% endblock %}">

    {% block style_base %}
        {% include "assets/styles.html" %}
        {% block extra_style %}{% endblock %}
    {% endblock %}

    {% block extra_head_base %}
        {% compress js %}
            <script src="{% static "components/sprockets-modernizr/modernizr.js" %}"></script>
        {% endcompress %}
        {% block extra_head %}{% endblock %}
    {% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}"
    {% block body_attrs %}{% endblock %}
    id="{% block body_id %}{% endblock %}">
    <div id="wrap">

        {% block topbar_base %}
        <header id="top-header">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        {% block topbar %}
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            {% block site_brand %}<a class="brand" href="{% url "home" %}">{% trans "Project Name" %}</a>{% endblock %}
                            <div class="nav-collapse">
                                {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
                            </div>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}

        <div class="container">
            <div id="messages-area">{% include "_messages.html" %}</div>
            {% block ieprompt %}{% endblock %}
            <div id="loading" class="loader" style="display: none;">{% trans "Loading" %}…</div>

            {% block page_header_base %}
                {% block page_header %}{% endblock %}
            {% endblock %}

            <div class="row">
                {% block content_base %}{% endblock %}
            </div>
        </div>

        <div id="push"></div>{# sticky footer push #}
    </div>{# /wrap #}

    {% block footer_base %}
        <footer id="footer">
            {% block footer %}{% include "_footer.html" %}{% endblock %}
        </footer>
    {% endblock %}

    {% block script_base %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static "components/jquery/jquery.js" %}"><\/script>')</script>
        {% include "assets/scripts.html" %}
        {% block extra_script %}{% endblock %}
    {% endblock %}

    {% block extra_body_base %}
        {% block extra_body %}{% endblock %}
    {% endblock %}

    {% block modal_base %}{% endblock %}
</body>
</html>